(defun close-error-window-and-run ()
  (interactive)
  (if (eq (length (window-list)) 2)
      ((lambda ()
         (quit-window nil (window-next-sibling))
    )))
  (evil-normal-state)
  (save-buffer)
  (org-ctrl-c-ctrl-c)
  )
