(global-set-key (kbd "<f9> a") 'rename-this-file)
(global-set-key (kbd "<f9> d") 'open-buffer-in-new-frame)
(global-set-key (kbd "<f9> f") 'grimoire-mode-search)
(global-set-key (kbd "<f9> g") 'helm-for-files)
(global-set-key (kbd "<f9> e") 'org-ctrl-c-ctrl-c)
(global-set-key (kbd "<f9> t") 'org-babel-tangle)
(global-set-key (kbd "<f9> x") 'delete-file-and-buffer)
(global-set-key (kbd "<f9> r") 'aws-run )
(global-set-key (kbd "<f9> 9") 'aws-add-file-to-run-buffer)
(global-set-key (kbd "<f9> <left>") 'previous-buffer)
(global-set-key (kbd "<f9> <right>") 'next-buffer)
(global-set-key (kbd "<f9> `") 'spacemacs/add-word-to-dict-global)
